# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  dsc_lib_config = debug
  dsc_tests_config = debug
endif
ifeq ($(config),release)
  dsc_lib_config = release
  dsc_tests_config = release
endif

PROJECTS := dsc-lib dsc-tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

dsc-lib:
ifneq (,$(dsc_lib_config))
	@echo "==== Building dsc-lib ($(dsc_lib_config)) ===="
	@${MAKE} --no-print-directory -C . -f dsc-lib.make config=$(dsc_lib_config)
endif

dsc-tests: dsc-lib
ifneq (,$(dsc_tests_config))
	@echo "==== Building dsc-tests ($(dsc_tests_config)) ===="
	@${MAKE} --no-print-directory -C . -f dsc-tests.make config=$(dsc_tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f dsc-lib.make clean
	@${MAKE} --no-print-directory -C . -f dsc-tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   dsc-lib"
	@echo "   dsc-tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"